### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by ShijianXu** [alexrame/diwa#1]
Hi,

Thank you for sharing the code.
When I was using your code, I think I found some problems. In the code [here](https://github.com/alexrame/diwa/blob/main/domainbed/lib/misc.py#L25), you try to get all the `env{i}_out_Accuracies/acc_net`. It was called [here](https://github.com/alexrame/diwa/blob/main/domainbed/scripts/diwa.py#L86). 

I think there is no such metric in the results, and the logic here is not right. If my `test_env=0`, then after first iteration, the for loop will break, and fails to collect the rest `env_i_acc`.

Can you take a look at it?

Best regards.

**Comment by alexrame** [comment]
Thank you for the feedback, and yes there was an inconsistency in the code. The default value of `metric_key="acc"` was appropriate. It's now fixed in the latest commit 8ee9724ae4fc3ec07910d176659cd0f11521a616.
