### ISSUE TITLE
getting error when downloading the data

### ISSUE THREAD

**Issue by sorobedio** [alexrame/diwa#2]
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by alexrame** [comment]
Please specify when such an error occurred. If this is related to datasets, please post your issue on [DomainBed](https://github.com/facebookresearch/DomainBed/tree/main/domainbed). I'm closing the topic until more information.

**Comment by sorobedio** [comment]
thank you it was my version of python i guess. i managed to download
