### ISSUE TITLE
What does test env  mean?

### ISSUE THREAD

**Issue by sorobedio** [alexrame/diwa#4]
In datasets files datasets classes define enviroment as a list by in the script file it is an integer.
also i used test_env =0 , trial_seed =0 with the default training code on OfficeHome and got accuracy arrpython -m scripts.diwa --data_dir=/input/domainbed/   --output_dir=sweep_output  --dataset OfficeHome --test_env 0 --weight_selection uniform --trial_seed 0ound 67% .
I used the following commands:
`python -m scripts.train --algorithm ERM --dataset OfficeHome --test_env 0 --init_step --path_for_init init_checkpoint.pth`
follown by:
`python -m scripts.sweep launch --data_dir /input/domainbed/ --output_dir sweep_output --command_launcher multi_gpu --datasets OfficeHome --test_env 0 --path_for_init init_checkpoint.pth --algorithms ERM --n_hparams 20 --n_trials 3`
 and 
`python -m scripts.diwa --data_dir=/input/domainbed/   --output_dir=sweep_output  --dataset OfficeHome --test_env 0 --weight_selection uniform --trial_seed 0`

Maybe that is due to my computer, but i am wondering if i am using the exact setting in the right way.
What is the  role of the variable --test_env ${test_env}
what are the possible values of test_env and their meaning?

thank you

**Comment by alexrame** [comment]
Thank you for your question.
In DomainBed, each contains multiple environments about the same classification task. And each environment is successively considered as the test while others are for training. The test_env is thus the current test environment. For example, there are 4 environments in OfficeHome, so test_env is between 0 and 3. Your $67$% seems consistent with the $67.3\pm0.2$ I obtained for test_env $=0$ for OfficeHome in Table8.

I hope this helps.
